openapi: 3.0.3
info:
  title: Seller / User Registration API
  version: 1.0.0
paths:
  /api/v1/auth/register:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [firstName,lastName,username,password,captchaToken,acceptTerms]
              properties:
                firstName:
                  type: string
                  minLength: 1
                lastName:
                  type: string
                  minLength: 1
                username:
                  type: string
                  minLength: 3
                  maxLength: 30
                password:
                  type: string
                captchaToken:
                  type: string
                email:
                  type: string
                  format: email
                acceptTerms:
                  type: boolean
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  username:
                    type: string
                  status:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
                  message:
                    type: string
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "401":
          description: Captcha failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "409":
          description: Username conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            http:
              type: integer
            message:
              type: string
            details:
              type: object
